apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org2
  name: cli
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: cli
    spec:
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: cli
          image: hyperledger/fabric-tools:2.0
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          env:
            - name: CHAINCODE_NAME
              value: "cc"
            - name: CHAINCODE_VERSION
              value: "1.0"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org2/users/Admin@org2/msp
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_ADDRESS
              value: peer0.org2:7051
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
            - name: GOPATH
              value: /opt/gopath
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
