---
apiVersion: v1
kind: Service
metadata:
  name: kafka0
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka0

---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka1

---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka2

---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka3
