---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka0
  name: kafka0
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: kafka0
    spec:
      hostname: kafka0
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk0-hs:2181,zk1-hs:2181,zk2-hs:2181
        image: hyperledger/fabric-kafka
        name: kafka0
        ports:
        - containerPort: 9092
      restartPolicy: Always
status: {}


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka1
  name: kafka1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: kafka1
    spec:
      hostname: kafka1
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk0-hs:2181,zk1-hs:2181,zk2-hs:2181
        image: hyperledger/fabric-kafka
        name: kafka1
        ports:
        - containerPort: 9092
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka2
  name: kafka2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: kafka2
    spec:
      hostname: kafka2
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk0-hs:2181,zk1-hs:2181,zk2-hs:2181
        image: hyperledger/fabric-kafka
        name: kafka2
        ports:
        - containerPort: 9092
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka3
  name: kafka3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: kafka3
    spec:
      hostname: kafka3
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk0-hs:2181,zk1-hs:2181,zk2-hs:2181
        image: hyperledger/fabric-kafka
        name: kafka3
        ports:
        - containerPort: 9092
      restartPolicy: Always
status: {}
