apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-tools
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: cli
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      containers:
      - name: fabric-tools
        image: hyperledger/fabric-tools:x86_64-1.1.0
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: CHAINCODE_NAME
          value: "cc"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESS
          value: blockchain-org1peer0:30110
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: GOPATH
          value: /opt/gopath
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
