---
apiVersion: v1
kind: Service
metadata:
  namespace: org1
  name: peer0
spec:
  selector:
    app: hyperledger
    role: peer
    peer-id: peer0
    org: org1
  type: NodePort
  ports:
  - name: externale-listen-endpoint
    protocol: TCP
    port: 7051
    targetPort: 7051
    nodePort: 30001

  - name: chaincode-listen
    protocol: TCP
    port: 7052
    targetPort: 7052
    nodePort: 30002

  - name: event-listen
    protocol: TCP
    port: 7053
    targetPort: 7053
    nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  namespace: org1
  name: peer1
spec:
  selector:
    app: hyperledger
    role: peer
    peer-id: peer1
    org: org1
  type: NodePort
  ports:
  - name: externale-listen-endpoint
    protocol: TCP
    port: 7051
    targetPort: 7051
    nodePort: 30004

  - name: chaincode-listen
    protocol: TCP
    port: 7052
    targetPort: 7052
    nodePort: 30005

  - name: event-listen
    protocol: TCP
    port: 7053
    targetPort: 7053
    nodePort: 30006

---
apiVersion: v1
kind: Service
metadata:
  namespace: org2
  name: peer0
spec:
  selector:
    app: hyperledger
    role: peer
    peer-id: peer0
    org: org2
  type: NodePort
  ports:
  - name: externale-listen-endpoint
    protocol: TCP
    port: 7051
    targetPort: 7051
    nodePort: 30101

  - name: chaincode-listen
    protocol: TCP
    port: 7052
    targetPort: 7052
    nodePort: 30102

  - name: event-listen
    protocol: TCP
    port: 7053
    targetPort: 7053
    nodePort: 30103

---
apiVersion: v1
kind: Service
metadata:
  namespace: org2
  name: peer1
spec:
  selector:
    app: hyperledger
    role: peer
    peer-id: peer1
    org: org2
  type: NodePort
  ports:
  - name: externale-listen-endpoint
    protocol: TCP
    port: 7051
    targetPort: 7051
    nodePort: 30104

  - name: chaincode-listen
    protocol: TCP
    port: 7052
    targetPort: 7052
    nodePort: 30105

  - name: event-listen
    protocol: TCP
    port: 7053
    targetPort: 7053
    nodePort: 30106
