---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1
  name: peer0-org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: peer
        peer-id: peer0
        org: org1
    spec:
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer0-org1
          image: hyperledger/fabric-peer:2.0
          command:
            [
              "sh",
              "-c",
              "sleep 1 && while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start",
            ]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ID
              value: peer0.org1
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0.org1:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0.org1:7051
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_COMMITTER_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer0.org1/msp/
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: goleveldb
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/
            - name: GODEBUG
              value: "netdns=go"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
            - mountPath: /host/var/run/docker.sock
              name: dockersocket

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1
  name: peer1-org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: peer
        peer-id: peer1
        org: org1
    spec:
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-peer:2.0
          command:
            [
              "sh",
              "-c",
              "sleep 1 && while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start",
            ]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ID
              value: peer1.org1
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer1.org1:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer1.org1:7051
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_COMMITTER_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer1.org1/msp/
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer1.org1/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer1.org1/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1/peers/peer1.org1/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: goleveldb
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/
            - name: GODEBUG
              value: "netdns=go"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
            - mountPath: /host/var/run/docker.sock
              name: dockersocket

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org2
  name: peer0-org2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: peer
        peer-id: peer0
        org: org2
    spec:
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer0-org2
          image: hyperledger/fabric-peer:2.0
          command:
            [
              "sh",
              "-c",
              "sleep 1 && while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start",
            ]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ID
              value: peer0.org2
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0.org2:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0.org2:7051
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_COMMITTER_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer0.org2/msp/
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer0.org2/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer0.org2/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer0.org2/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: goleveldb
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/
            - name: GODEBUG
              value: "netdns=go"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
            - mountPath: /host/var/run/docker.sock
              name: dockersocket

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org2
  name: peer1-org2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: peer
        peer-id: peer1
        org: org2
    spec:
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer1-org2
          image: hyperledger/fabric-peer:2.0
          command:
            [
              "sh",
              "-c",
              "sleep 1 && while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start",
            ]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ID
              value: peer1.org2
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer1.org2:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer1.org2:7051
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_COMMITTER_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer1.org2/msp/
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer1.org2/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer1.org2/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2/peers/peer1.org2/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: goleveldb
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/
            - name: GODEBUG
              value: "netdns=go"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
